import type { RequiredDataFromCollectionSlug } from 'payload'

/** Lexical heading for form section dividers (Form block type: message). */
function sectionMessage(heading: string, blockName: string) {
  return {
    blockType: 'message' as const,
    blockName,
    message: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: heading,
                version: 1,
              },
            ],
            direction: 'ltr' as const,
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr' as const,
        format: '',
        indent: 0,
        version: 1,
      },
    },
  }
}

export const speakingRequestFormData = {
  title: 'Speaking Request',
  submitButtonLabel: 'Submit speaking request',
  confirmationType: 'message',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          tag: 'h2',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Thank you — your speaking request was received.',
              version: 1,
            },
          ],
          direction: 'ltr' as const,
          format: '',
          indent: 0,
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'We will review your details and follow up by email.',
              version: 1,
            },
          ],
          direction: 'ltr' as const,
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr' as const,
      format: '',
      indent: 0,
      version: 1,
    },
  },
  emails: [
    {
      emailFrom: '"Erin Jerri" <youremail@domain.com>',
      emailTo: '{{contactme@erinjerri.xyz}}',
      subject: 'New speaking request',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'A new speaking request was submitted.',
                  version: 1,
                },
              ],
              direction: 'ltr' as const,
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr' as const,
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],
  fields: [
    sectionMessage('1. Contact info', 'section-contact'),
    {
      name: 'full-name',
      blockName: 'full-name',
      blockType: 'text',
      label: 'Full name',
      required: true,
      width: 100,
    },
    {
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email address',
      required: true,
      width: 100,
    },
    {
      name: 'phone',
      blockName: 'phone',
      blockType: 'text',
      label: 'Phone number (optional)',
      required: false,
      width: 100,
    },
    {
      name: 'company',
      blockName: 'company',
      blockType: 'text',
      label: 'Company / organization name',
      required: true,
      width: 100,
    },
    {
      name: 'website-url',
      blockName: 'website-url',
      blockType: 'text',
      label: 'Website or LinkedIn URL (optional)',
      required: false,
      width: 100,
    },

    sectionMessage('2. Event details', 'section-event'),
    {
      name: 'event-name',
      blockName: 'event-name',
      blockType: 'text',
      label: 'Event name',
      required: true,
      width: 100,
    },
    {
      name: 'event-type',
      blockName: 'event-type',
      blockType: 'select',
      label: 'Event type',
      required: true,
      width: 100,
      options: [
        { label: 'Conference', value: 'conference' },
        { label: 'Corporate event', value: 'corporate' },
        { label: 'Workshop / training', value: 'workshop' },
        { label: 'University / academic', value: 'university' },
        { label: 'Podcast / interview', value: 'podcast' },
        { label: 'Panel', value: 'panel' },
        { label: 'Other', value: 'other' },
      ],
    },
    {
      name: 'event-date-start',
      blockName: 'event-date-start',
      blockType: 'text',
      label: 'Event date(s) start (single date or date range)',
      required: false,
      width: 100,
    },
    {
      name: 'event-date-end',
      blockName: 'event-date-end',
      blockType: 'text',
      label: 'Event date(s) end (optional for range)',
      required: false,
      width: 100,
    },
    {
      name: 'event-location',
      blockName: 'event-location',
      blockType: 'text',
      label: 'Event location (City, State/Country or "Virtual")',
      required: true,
      width: 100,
    },
    {
      name: 'audience-size',
      blockName: 'audience-size',
      blockType: 'select',
      label: 'Expected audience size',
      required: true,
      width: 100,
      options: [
        { label: '<50', value: 'lt50' },
        { label: '50–100', value: '50-100' },
        { label: '100–500', value: '100-500' },
        { label: '500–1,000', value: '500-1000' },
        { label: '1,000+', value: '1000plus' },
      ],
    },
    {
      name: 'audience-type-engineers',
      blockName: 'audience-type-engineers',
      blockType: 'checkbox',
      label: 'Audience type: Engineers',
      required: false,
      width: 50,
    },
    {
      name: 'audience-type-executives',
      blockName: 'audience-type-executives',
      blockType: 'checkbox',
      label: 'Audience type: Executives',
      required: false,
      width: 50,
    },
    {
      name: 'audience-type-founders',
      blockName: 'audience-type-founders',
      blockType: 'checkbox',
      label: 'Audience type: Founders / Startups',
      required: false,
      width: 50,
    },
    {
      name: 'audience-type-creatives',
      blockName: 'audience-type-creatives',
      blockType: 'checkbox',
      label: 'Audience type: Creatives',
      required: false,
      width: 50,
    },
    {
      name: 'audience-type-students',
      blockName: 'audience-type-students',
      blockType: 'checkbox',
      label: 'Audience type: Students',
      required: false,
      width: 50,
    },
    {
      name: 'audience-type-general',
      blockName: 'audience-type-general',
      blockType: 'checkbox',
      label: 'Audience type: General audience',
      required: false,
      width: 50,
    },
    {
      name: 'audience-type-other',
      blockName: 'audience-type-other',
      blockType: 'text',
      label: 'Audience type: Other (optional)',
      required: false,
      width: 100,
    },

    sectionMessage('3. Speaking request details', 'section-speaking'),
    {
      name: 'topic-ai-agentic-systems',
      blockName: 'topic-ai-agentic-systems',
      blockType: 'checkbox',
      label: 'What topic(s) are you interested in? AI & Agentic Systems',
      required: false,
      width: 50,
    },
    {
      name: 'topic-spatial-computing',
      blockName: 'topic-spatial-computing',
      blockType: 'checkbox',
      label: 'What topic(s) are you interested in? Spatial Computing (AR/VR/XR)',
      required: false,
      width: 50,
    },
    {
      name: 'topic-future-of-work',
      blockName: 'topic-future-of-work',
      blockType: 'checkbox',
      label: 'What topic(s) are you interested in? Future of Work & Productivity',
      required: false,
      width: 50,
    },
    {
      name: 'topic-multimodal-interfaces',
      blockName: 'topic-multimodal-interfaces',
      blockType: 'checkbox',
      label: 'What topic(s) are you interested in? Multimodal Interfaces',
      required: false,
      width: 50,
    },
    {
      name: 'topic-ai-creativity',
      blockName: 'topic-ai-creativity',
      blockType: 'checkbox',
      label: 'What topic(s) are you interested in? AI + Creativity (Games, Film, Media)',
      required: false,
      width: 50,
    },
    {
      name: 'topic-woc-tech-leadership',
      blockName: 'topic-woc-tech-leadership',
      blockType: 'checkbox',
      label: 'What topic(s) are you interested in? Women of Color in Tech / Leadership',
      required: false,
      width: 50,
    },
    {
      name: 'topic-founder-journey',
      blockName: 'topic-founder-journey',
      blockType: 'checkbox',
      label: 'What topic(s) are you interested in? Startup / Founder Journey',
      required: false,
      width: 50,
    },
    {
      name: 'topic-custom-selected',
      blockName: 'topic-custom-selected',
      blockType: 'checkbox',
      label: 'What topic(s) are you interested in? Custom Topic',
      required: false,
      width: 50,
    },
    {
      name: 'topic-custom-details',
      blockName: 'topic-custom-details',
      blockType: 'text',
      label: 'Custom topic details (required if Custom Topic selected)',
      required: false,
      width: 100,
    },
    {
      name: 'talk-goals',
      blockName: 'talk-goals',
      blockType: 'textarea',
      label: 'Describe your goals for this talk (what should the audience walk away with?)',
      required: true,
      width: 100,
    },
    {
      name: 'preferred-format',
      blockName: 'preferred-format',
      blockType: 'select',
      label: 'Preferred format',
      required: true,
      width: 100,
      options: [
        { label: 'Keynote', value: 'keynote' },
        { label: 'Fireside chat', value: 'fireside' },
        { label: 'Panel', value: 'panel' },
        { label: 'Workshop', value: 'workshop' },
        { label: 'Custom', value: 'custom' },
      ],
    },
    {
      name: 'talk-duration',
      blockName: 'talk-duration',
      blockType: 'select',
      label: 'Requested talk duration',
      required: true,
      width: 100,
      options: [
        { label: '30 min', value: '30' },
        { label: '45 min', value: '45' },
        { label: '60 min', value: '60' },
        { label: '90+ min / workshop', value: '90plus' },
      ],
    },

    sectionMessage('4. Logistics & budget (important for filtering)', 'section-logistics'),
    {
      name: 'paid-engagement',
      blockName: 'paid-engagement',
      blockType: 'select',
      label: 'Is this a paid speaking engagement?',
      required: true,
      width: 100,
      options: [
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' },
        { label: 'Not sure yet', value: 'unsure' },
      ],
    },
    {
      name: 'budget-range',
      blockName: 'budget-range',
      blockType: 'select',
      label: 'Budget range',
      required: false,
      width: 100,
      options: [
        { label: '$1,000–$2,500', value: '1k-2500' },
        { label: '$2,500–$5,000', value: '2500-5k' },
        { label: '$5,000–$10,000', value: '5k-10k' },
        { label: '$10,000+', value: '10kplus' },
        { label: 'Not yet defined', value: 'tbd' },
      ],
    },
    {
      name: 'travel-required',
      blockName: 'travel-required',
      blockType: 'select',
      label: 'Will travel be required?',
      required: true,
      width: 100,
      options: [
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' },
      ],
    },
    {
      name: 'travel-covered',
      blockName: 'travel-covered',
      blockType: 'select',
      label: 'If travel is required, will travel + accommodations be covered?',
      required: false,
      width: 100,
      options: [
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' },
      ],
    },

    sectionMessage('5. Additional context', 'section-extra'),
    {
      name: 'additional-notes',
      blockName: 'additional-notes',
      blockType: 'textarea',
      label: 'Additional notes or requests',
      required: false,
      width: 100,
    },
    {
      name: 'brief-upload-link',
      blockName: 'brief-upload-link',
      blockType: 'text',
      label: 'Upload event brief / deck (optional) — share file link',
      required: false,
      width: 100,
    },

    sectionMessage('6. Qualification (optional but highly recommended)', 'section-qualification'),
    {
      name: 'referral-source',
      blockName: 'referral-source',
      blockType: 'text',
      label: 'How did you hear about me?',
      required: false,
      width: 100,
    },
    {
      name: 'why-me',
      blockName: 'why-me',
      blockType: 'text',
      label: 'Why are you interested in having me speak specifically?',
      required: false,
      width: 100,
    },
  ],
  redirect: undefined,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
} as RequiredDataFromCollectionSlug<'forms'>
